Входные данные

8 5

5

3 3 4

3 4 3

1 1 2

3 4 3

3 5 4

In [1]:
import numpy as np

In [2]:
def get_matrix(n, m, w):
    res = np.empty([n, m])
    res.fill(w)
    return res

In [3]:
N, M = map(int, input().split())

A = get_matrix(N, M, 0)

k = int(input())
Bs = []
B_used = []
for i in range(k):
    n, m, w = map(int, input().split())
    B = get_matrix(n, m, w)
    Bs.append(B)
    B_used.append(False)
Bs.sort(key=lambda x: x.shape[1], reverse=True)

A, Bs

8 5
5
3 3 4
3 4 3
1 1 2
3 4 3
3 5 4


(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 [array([[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]]),
  array([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
  array([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
  array([[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]),
  array([[2.]])])

In [5]:
def can_insert_submatrix(B, r, c):
    Ar, Ac = A.shape
    Br, Bc = B.shape
    if r + Br > Ar or c + Bc > Ac:
        return False
    return np.sum(A[r:r+Br, c:c+Bc]) == 0

In [6]:
def insert_submatrix(B, r, c, fill_zeros = False):
    Br, Bc = B.shape
    A[r:r+Br, c:c+Bc] = 0 if fill_zeros else B

In [7]:
def get_unused_B_indices():
    return [i for i in range(k) if not B_used[i]]

In [8]:
def calc_A_max():
    global A, A_max
    
    B_indices = get_unused_B_indices()
    if len(B_indices) == 0:
        return
    for B_i in B_indices:
        B_used[B_i] = True
        for i in range(N):
            for j in range(M):
                if can_insert_submatrix(Bs[B_i], i, j):
                    insert_submatrix(Bs[B_i], i, j)
                    calc_A_max()
                    if np.sum(A) > np.sum(A_max):
                        A_max = A.copy()
                    insert_submatrix(Bs[B_i], i, j, True)
        B_used[B_i] = False

In [9]:
A_max = A.copy()
calc_A_max()

In [10]:
A_max

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 2.],
       [3., 3., 3., 3., 0.],
       [3., 3., 3., 3., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Максимум среди минимумов по столбцам

In [27]:
min_column = np.min(A_max, axis=0)
ind_row = np.argmin(A_max, axis=0)
print ("Минимумы по столбцам: ",min_column,"\nНомера строк минимумов: ", ind_row)

Минимумы по столбцам:  [0. 0. 0. 0. 0.] 
Номера строк минимумов:  [6 6 6 6 4]


In [28]:
max_min_column = max(min_column)
ind_column = np.argmax(max_min_column)
print("Максимум среди минимумов по столбцам: ", max_min_column,"\nКоординаты: (",ind_row[ind_column],";",ind_column,")")

Максимум среди минимумов по столбцам:  0.0 
Координаты: ( 6 ; 0 )


Максимум среди минимумов по строкам

In [29]:
min_row = np.min(A_max, axis=1)
ind_column = np.argmin(A_max, axis=1)
print ("Минимумы по строкам: ",min_row,"\nНомера столбцов минимумов: ", ind_column)

Минимумы по строкам:  [4. 4. 4. 2. 0. 0. 0. 0.] 
Номера столбцов минимумов:  [0 0 0 4 4 4 0 0]


In [30]:
max_min_row = max(min_row)
ind_row = np.argmax(max_min_row)
print("Максимум среди минимумов по строкам: ", max_min_row,"\nКоординаты: (",ind_row,";",ind_column[ind_row],")")

Максимум среди минимумов по строкам:  4.0 
Координаты: ( 0 ; 0 )
